Django Framework/workshop1/workshop1/urls.py
from django.contrib import admin
from django.urls import path

from workshop1.petstagram.views.generic import show_home, show_dashboard
from workshop1.petstagram.views.pet import edit_pet, delete_pet, add_pet
from workshop1.petstagram.views.photos import edit_pet_photo, like_pet_photo, create_pet_photo, show_photo_details
from workshop1.petstagram.views.profile import show_profile, create_profile, edit_profile, delete_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', show_home, name='home'),
    path('dashboard/', show_dashboard, name='dashboard'),

    path('profile/', show_profile, name='profile'),

    path('profile/create/', create_profile, name='create profile'),

    path('profile/edit//', edit_profile, name='edit profile'),
    path('profile/delete/', delete_profile, name='delete profile'),

    path('photo/details/<int:pk>', show_photo_details, name='pet photo details'),
    path('photo/add/', create_pet_photo, name='create photo'),
    path('photo/edit/<int:pk>/', edit_pet_photo, name='edit pet photo'),
    path('photo/like/<int:pk>/', like_pet_photo, name='like pet photo'),
    path('pet/add/', add_pet, name='create pet'),
    path('pet/edit/<int:pk>/', edit_pet, name='edit pet'),
    path('pet/delete/<int:pk>/', delete_pet, name='delete pet'),

]

Django Framework/workshop1/workshop1/petstagram/models.py
from django.core import validators
from django.db import models

# Create your models here.
from workshop1.petstagram.validators import validate_only_letters, max_size


class Profile(models.Model):
    MALE = 'Male'
    FEMALE = 'Female'
    DO_NOT_ASK = 'Do not ask'
    GENDER = [(x, x) for x in (MALE, FEMALE, DO_NOT_ASK)]

    first_name = models.CharField(
        max_length=30,
        validators=(
            validators.MinLengthValidator(2),
            validate_only_letters
        )
    )

    last_name = models.CharField(
        max_length=30,
        validators=(
            validators.MinLengthValidator(2),
            validate_only_letters
        )
    )

    profile_picture = models.URLField(
        validators=(max_size,)
    )

    date_of_birth = models.DateField(
        null=True,
        blank=True
    )

    description = models.TextField(
        null=True,
        blank=True
    )
    e_mail = models.EmailField(
        null=True,
        blank=True
    )
    gender = models.CharField(
        max_length=max(len(x) for x, _ in GENDER),
        choices=GENDER,
        null=True,
        blank=True,
    )


class Pet(models.Model):
    """
    "Dog", "Bunny", "Parrot", "Fish", or "Other".
    """
    CAT = 'Cat'
    DOG = 'Dog'
    BUNNY = 'Bunny'
    PARROT = 'Parrot'
    FISH = 'Fish'
    OTHER = 'Other'
    TYPES = [CAT, DOG, BUNNY, PARROT, FISH, OTHER]
    CHOICES = [(x, x) for x in TYPES]

    name = models.CharField(
        max_length=30,
    )

    type = models.CharField(
        max_length=max(len(x) for x in TYPES),
        choices=CHOICES
    )

    date_of_birth = models.DateField(
        null=True,
        blank=True,
    )
    user_profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE
    )

    class Meta:
        unique_together = ('name', 'user_profile')


class PetPhoto(models.Model):
    photo = models.ImageField(
        validators=(
            max_size,
        )
    )

    tagged_pets = models.ManyToManyField(Pet)

    description = models.TextField()

    date_time_of_publication = models.DateTimeField(
        auto_now_add=True
    )

    likes = models.IntegerField(
        default=0
    )

Django Framework/workshop1/templates/part2/pet_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <!-- Form for Adding Pet -->
            <form method="post" action="profile_details.html">
                <div class="form-group">
                    <label for="name">Pet Name</label>
                    <input type="text" class="form-control" name="first_name" placeholder="Enter name"
                           id="name"/>
                </div>
                <div class="form-group">
                    <label for="type_animal" class="col-form-label">Type:
                    <select class="form-select">
                        <option value="first">Cat</option>
                        <option value="second">Dog</option>
                        <option value="third">Mouse</option>
                    </select></label>
                </div>
                <div class="form-group">
                    <label for="age">Day of Birth:</label>
                    <input type="date" class="form-control" name="age" placeholder=""
                           id="age"/>
                </div>

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
            <!-- End Form for Adding Pet -->
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

Django Framework/workshop1/templates/part2/pet_create.html
{% extends 'base/base.html' %}
{% block content %}
    <h1 class="text-center">Add Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="{% url 'create pet' %}">
                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

Django Framework/workshop1/templates/part2/pet_delete.html
{% extends 'base/base.html' %}
{% block content %}
    <h1 class="text-center">Delete Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'delete pet' pet.pk %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-danger mt-2" type="submit">Delete</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

Django Framework/workshop1/templates/part2/pet_edit.html
{% extends 'base/base.html' %}
{% block content %}
    <h1 class="text-center">Edit Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet' pet.pk %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

Django Framework/workshop1/templates/part2/photo_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <!-- Form for Adding Photos -->
            <form method="post" action="dashboard.html">
                <div class="custom-file">
                    <label for="file-upload">Pet Image</label>
                    <input type="file" id="file-upload" class="form-control-file" name="filename">
                </div>
                <div class="form-group">
                    <label for="first_name">Description</label>
                    <textarea class="form-control" name="first_name" placeholder="Enter Description"
                              id="first_name" rows="3"></textarea>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="checkbox">
                    <label class="custom-control-label" for="checkbox">Tom</label><br>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="second-checkbox">
                    <label class="custom-control-label" for="second-checkbox">Jerry</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="third-checkbox">
                    <label class="custom-control-label" for="third-checkbox">Spike</label>
                </div>

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
            <!-- End Form for Adding Photos -->

        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

Django Framework/workshop1/templates/part2/photo_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Add a New Pet Photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="dashboard.html">

                <!-- Form for Adding Photos -->

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

Django Framework/workshop1/templates/part2/photo_edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container mb-5 ">
    <h1 class="text-center">Edit Pet Photo</h1>
    <img src="https://images.unsplash.com/photo-1623387641168-d9803ddd3f35?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGV0c3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"
         class="w-50 rounded mx-auto d-block" alt="Photo description">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="photo_details.html">

                <!-- Form for Editing a Photo -->

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

Django Framework/workshop1/templates/part2/profile_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index-page' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile-page' %}">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form>
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" name="first_name" maxlength="30" required
                           placeholder="Enter first name" id="first_name"/>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <input type="text" class="form-control" name="last_name" maxlength="30" required
                           placeholder="Enter last name" id="id_last_name"/>
                </div>
                <div class="form-group">
                    <label for="id_image">Link to Profile Image</label>
                    <input type="url" class="form-control" name="profile_image" required id="id_image"
                    placeholder="Enter URL"/>
                </div>
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</html>

Django Framework/workshop1/templates/part2/profile_create.html
{% extends 'base/base.html' %}
{% block content %}
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="{% url 'create profile' %}">
                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

Django Framework/workshop1/templates/part2/profile_delete.html
{% extends 'base/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete your profile?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'delete profile'%}">
                        {% csrf_token %}
                        <!-- For for Deleting a Profile -->

                        <input type="submit" value="Confirm" class="btn btn-danger"/>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Django Framework/workshop1/templates/part2/profile_edit.html
{% extends 'base/base.html' %}
{% block content %}
    <h1 class="text-center">Edit Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="{% url 'edit profile'%}">
                {% csrf_token %}
                {{ profile_form }}

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}